version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  AfterInstall:
    - location: scripts/install_ngnix.sh
      timeout: 180
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_nginx.sh
      timeout: 180
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop_nginx.sh
      timeout: 180
      runas: ubuntu

