version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
  build:
    commands:
      - echo Build completed on `date`
      - echo Preparing nginx files

artifacts:
  files:
    - '**/*'
